// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rusk.proto

package rusk

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

type EchoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{1}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

// List of transactions to be validated
type ValidateStateTransitionRequest struct {
	Calls                []*ContractCall `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ValidateStateTransitionRequest) Reset()         { *m = ValidateStateTransitionRequest{} }
func (m *ValidateStateTransitionRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateStateTransitionRequest) ProtoMessage()    {}
func (*ValidateStateTransitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{2}
}

func (m *ValidateStateTransitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateStateTransitionRequest.Unmarshal(m, b)
}
func (m *ValidateStateTransitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateStateTransitionRequest.Marshal(b, m, deterministic)
}
func (m *ValidateStateTransitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateStateTransitionRequest.Merge(m, src)
}
func (m *ValidateStateTransitionRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateStateTransitionRequest.Size(m)
}
func (m *ValidateStateTransitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateStateTransitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateStateTransitionRequest proto.InternalMessageInfo

func (m *ValidateStateTransitionRequest) GetCalls() []*ContractCall {
	if m != nil {
		return m.Calls
	}
	return nil
}

type ContractCall struct {
	// Types that are valid to be assigned to ContractCall:
	//	*ContractCall_Tx
	//	*ContractCall_Withdraw
	//	*ContractCall_Stake
	//	*ContractCall_Bid
	//	*ContractCall_Slash
	//	*ContractCall_Distribute
	//	*ContractCall_WithdrawStake
	//	*ContractCall_WithdrawBid
	ContractCall         isContractCall_ContractCall `protobuf_oneof:"contract_call"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ContractCall) Reset()         { *m = ContractCall{} }
func (m *ContractCall) String() string { return proto.CompactTextString(m) }
func (*ContractCall) ProtoMessage()    {}
func (*ContractCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{3}
}

func (m *ContractCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractCall.Unmarshal(m, b)
}
func (m *ContractCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractCall.Marshal(b, m, deterministic)
}
func (m *ContractCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractCall.Merge(m, src)
}
func (m *ContractCall) XXX_Size() int {
	return xxx_messageInfo_ContractCall.Size(m)
}
func (m *ContractCall) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractCall.DiscardUnknown(m)
}

var xxx_messageInfo_ContractCall proto.InternalMessageInfo

type isContractCall_ContractCall interface {
	isContractCall_ContractCall()
}

type ContractCall_Tx struct {
	Tx *Transaction `protobuf:"bytes,1,opt,name=tx,proto3,oneof"`
}

type ContractCall_Withdraw struct {
	Withdraw *WithdrawRequest `protobuf:"bytes,2,opt,name=withdraw,proto3,oneof"`
}

type ContractCall_Stake struct {
	Stake *StakeRequest `protobuf:"bytes,3,opt,name=stake,proto3,oneof"`
}

type ContractCall_Bid struct {
	Bid *BidRequest `protobuf:"bytes,4,opt,name=bid,proto3,oneof"`
}

type ContractCall_Slash struct {
	Slash *SlashRequest `protobuf:"bytes,5,opt,name=slash,proto3,oneof"`
}

type ContractCall_Distribute struct {
	Distribute *DistributeRequest `protobuf:"bytes,6,opt,name=distribute,proto3,oneof"`
}

type ContractCall_WithdrawStake struct {
	WithdrawStake *WithdrawStakeRequest `protobuf:"bytes,7,opt,name=withdraw_stake,json=withdrawStake,proto3,oneof"`
}

type ContractCall_WithdrawBid struct {
	WithdrawBid *WithdrawBidRequest `protobuf:"bytes,8,opt,name=withdraw_bid,json=withdrawBid,proto3,oneof"`
}

func (*ContractCall_Tx) isContractCall_ContractCall() {}

func (*ContractCall_Withdraw) isContractCall_ContractCall() {}

func (*ContractCall_Stake) isContractCall_ContractCall() {}

func (*ContractCall_Bid) isContractCall_ContractCall() {}

func (*ContractCall_Slash) isContractCall_ContractCall() {}

func (*ContractCall_Distribute) isContractCall_ContractCall() {}

func (*ContractCall_WithdrawStake) isContractCall_ContractCall() {}

func (*ContractCall_WithdrawBid) isContractCall_ContractCall() {}

func (m *ContractCall) GetContractCall() isContractCall_ContractCall {
	if m != nil {
		return m.ContractCall
	}
	return nil
}

func (m *ContractCall) GetTx() *Transaction {
	if x, ok := m.GetContractCall().(*ContractCall_Tx); ok {
		return x.Tx
	}
	return nil
}

func (m *ContractCall) GetWithdraw() *WithdrawRequest {
	if x, ok := m.GetContractCall().(*ContractCall_Withdraw); ok {
		return x.Withdraw
	}
	return nil
}

func (m *ContractCall) GetStake() *StakeRequest {
	if x, ok := m.GetContractCall().(*ContractCall_Stake); ok {
		return x.Stake
	}
	return nil
}

func (m *ContractCall) GetBid() *BidRequest {
	if x, ok := m.GetContractCall().(*ContractCall_Bid); ok {
		return x.Bid
	}
	return nil
}

func (m *ContractCall) GetSlash() *SlashRequest {
	if x, ok := m.GetContractCall().(*ContractCall_Slash); ok {
		return x.Slash
	}
	return nil
}

func (m *ContractCall) GetDistribute() *DistributeRequest {
	if x, ok := m.GetContractCall().(*ContractCall_Distribute); ok {
		return x.Distribute
	}
	return nil
}

func (m *ContractCall) GetWithdrawStake() *WithdrawStakeRequest {
	if x, ok := m.GetContractCall().(*ContractCall_WithdrawStake); ok {
		return x.WithdrawStake
	}
	return nil
}

func (m *ContractCall) GetWithdrawBid() *WithdrawBidRequest {
	if x, ok := m.GetContractCall().(*ContractCall_WithdrawBid); ok {
		return x.WithdrawBid
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ContractCall) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ContractCall_Tx)(nil),
		(*ContractCall_Withdraw)(nil),
		(*ContractCall_Stake)(nil),
		(*ContractCall_Bid)(nil),
		(*ContractCall_Slash)(nil),
		(*ContractCall_Distribute)(nil),
		(*ContractCall_WithdrawStake)(nil),
		(*ContractCall_WithdrawBid)(nil),
	}
}

type ValidateStateTransitionResponse struct {
	SuccessfulCalls      []*ContractCall `protobuf:"bytes,1,rep,name=successful_calls,json=successfulCalls,proto3" json:"successful_calls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ValidateStateTransitionResponse) Reset()         { *m = ValidateStateTransitionResponse{} }
func (m *ValidateStateTransitionResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateStateTransitionResponse) ProtoMessage()    {}
func (*ValidateStateTransitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{4}
}

func (m *ValidateStateTransitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateStateTransitionResponse.Unmarshal(m, b)
}
func (m *ValidateStateTransitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateStateTransitionResponse.Marshal(b, m, deterministic)
}
func (m *ValidateStateTransitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateStateTransitionResponse.Merge(m, src)
}
func (m *ValidateStateTransitionResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateStateTransitionResponse.Size(m)
}
func (m *ValidateStateTransitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateStateTransitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateStateTransitionResponse proto.InternalMessageInfo

func (m *ValidateStateTransitionResponse) GetSuccessfulCalls() []*ContractCall {
	if m != nil {
		return m.SuccessfulCalls
	}
	return nil
}

type ExecuteStateTransitionResponse struct {
	Calls                []*ContractCall `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExecuteStateTransitionResponse) Reset()         { *m = ExecuteStateTransitionResponse{} }
func (m *ExecuteStateTransitionResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteStateTransitionResponse) ProtoMessage()    {}
func (*ExecuteStateTransitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{5}
}

func (m *ExecuteStateTransitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStateTransitionResponse.Unmarshal(m, b)
}
func (m *ExecuteStateTransitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStateTransitionResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteStateTransitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStateTransitionResponse.Merge(m, src)
}
func (m *ExecuteStateTransitionResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteStateTransitionResponse.Size(m)
}
func (m *ExecuteStateTransitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStateTransitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStateTransitionResponse proto.InternalMessageInfo

func (m *ExecuteStateTransitionResponse) GetCalls() []*ContractCall {
	if m != nil {
		return m.Calls
	}
	return nil
}

type ExecuteStateTransitionRequest struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteStateTransitionRequest) Reset()         { *m = ExecuteStateTransitionRequest{} }
func (m *ExecuteStateTransitionRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteStateTransitionRequest) ProtoMessage()    {}
func (*ExecuteStateTransitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{6}
}

func (m *ExecuteStateTransitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStateTransitionRequest.Unmarshal(m, b)
}
func (m *ExecuteStateTransitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStateTransitionRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteStateTransitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStateTransitionRequest.Merge(m, src)
}
func (m *ExecuteStateTransitionRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteStateTransitionRequest.Size(m)
}
func (m *ExecuteStateTransitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStateTransitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStateTransitionRequest proto.InternalMessageInfo

func (m *ExecuteStateTransitionRequest) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GenerateSecretKeyRequest struct {
	B                    []byte   `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateSecretKeyRequest) Reset()         { *m = GenerateSecretKeyRequest{} }
func (m *GenerateSecretKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateSecretKeyRequest) ProtoMessage()    {}
func (*GenerateSecretKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{7}
}

func (m *GenerateSecretKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateSecretKeyRequest.Unmarshal(m, b)
}
func (m *GenerateSecretKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateSecretKeyRequest.Marshal(b, m, deterministic)
}
func (m *GenerateSecretKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateSecretKeyRequest.Merge(m, src)
}
func (m *GenerateSecretKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateSecretKeyRequest.Size(m)
}
func (m *GenerateSecretKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateSecretKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateSecretKeyRequest proto.InternalMessageInfo

func (m *GenerateSecretKeyRequest) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

// Used for scanning unspent input set
type OwnedNotesResponse struct {
	Notes                []*DecryptedNote `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OwnedNotesResponse) Reset()         { *m = OwnedNotesResponse{} }
func (m *OwnedNotesResponse) String() string { return proto.CompactTextString(m) }
func (*OwnedNotesResponse) ProtoMessage()    {}
func (*OwnedNotesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{8}
}

func (m *OwnedNotesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnedNotesResponse.Unmarshal(m, b)
}
func (m *OwnedNotesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnedNotesResponse.Marshal(b, m, deterministic)
}
func (m *OwnedNotesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnedNotesResponse.Merge(m, src)
}
func (m *OwnedNotesResponse) XXX_Size() int {
	return xxx_messageInfo_OwnedNotesResponse.Size(m)
}
func (m *OwnedNotesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnedNotesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OwnedNotesResponse proto.InternalMessageInfo

func (m *OwnedNotesResponse) GetNotes() []*DecryptedNote {
	if m != nil {
		return m.Notes
	}
	return nil
}

// Call from CLI directly
type NewTransactionRequest struct {
	Sk                   *SecretKey       `protobuf:"bytes,1,opt,name=sk,proto3" json:"sk,omitempty"`
	Inputs               []*DecryptedNote `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Recipient            *PublicKey       `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Value                uint64           `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Fee                  uint64           `protobuf:"fixed64,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Obfuscated           bool             `protobuf:"varint,6,opt,name=obfuscated,proto3" json:"obfuscated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NewTransactionRequest) Reset()         { *m = NewTransactionRequest{} }
func (m *NewTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*NewTransactionRequest) ProtoMessage()    {}
func (*NewTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{9}
}

func (m *NewTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTransactionRequest.Unmarshal(m, b)
}
func (m *NewTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTransactionRequest.Marshal(b, m, deterministic)
}
func (m *NewTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransactionRequest.Merge(m, src)
}
func (m *NewTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_NewTransactionRequest.Size(m)
}
func (m *NewTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransactionRequest proto.InternalMessageInfo

func (m *NewTransactionRequest) GetSk() *SecretKey {
	if m != nil {
		return m.Sk
	}
	return nil
}

func (m *NewTransactionRequest) GetInputs() []*DecryptedNote {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *NewTransactionRequest) GetRecipient() *PublicKey {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *NewTransactionRequest) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NewTransactionRequest) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *NewTransactionRequest) GetObfuscated() bool {
	if m != nil {
		return m.Obfuscated
	}
	return false
}

type VerifyTransactionResponse struct {
	Verified             bool     `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTransactionResponse) Reset()         { *m = VerifyTransactionResponse{} }
func (m *VerifyTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyTransactionResponse) ProtoMessage()    {}
func (*VerifyTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{10}
}

func (m *VerifyTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTransactionResponse.Unmarshal(m, b)
}
func (m *VerifyTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTransactionResponse.Marshal(b, m, deterministic)
}
func (m *VerifyTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTransactionResponse.Merge(m, src)
}
func (m *VerifyTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyTransactionResponse.Size(m)
}
func (m *VerifyTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTransactionResponse proto.InternalMessageInfo

func (m *VerifyTransactionResponse) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

type KeysResponse struct {
	Vk                   *ViewKey   `protobuf:"bytes,1,opt,name=vk,proto3" json:"vk,omitempty"`
	Pk                   *PublicKey `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *KeysResponse) Reset()         { *m = KeysResponse{} }
func (m *KeysResponse) String() string { return proto.CompactTextString(m) }
func (*KeysResponse) ProtoMessage()    {}
func (*KeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{11}
}

func (m *KeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysResponse.Unmarshal(m, b)
}
func (m *KeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysResponse.Marshal(b, m, deterministic)
}
func (m *KeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysResponse.Merge(m, src)
}
func (m *KeysResponse) XXX_Size() int {
	return xxx_messageInfo_KeysResponse.Size(m)
}
func (m *KeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeysResponse proto.InternalMessageInfo

func (m *KeysResponse) GetVk() *ViewKey {
	if m != nil {
		return m.Vk
	}
	return nil
}

func (m *KeysResponse) GetPk() *PublicKey {
	if m != nil {
		return m.Pk
	}
	return nil
}

type GenerateScoreRequest struct {
	D                    []byte   `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`
	K                    []byte   `protobuf:"bytes,2,opt,name=k,proto3" json:"k,omitempty"`
	Y                    []byte   `protobuf:"bytes,3,opt,name=y,proto3" json:"y,omitempty"`
	YInv                 []byte   `protobuf:"bytes,4,opt,name=y_inv,json=yInv,proto3" json:"y_inv,omitempty"`
	Q                    []byte   `protobuf:"bytes,5,opt,name=q,proto3" json:"q,omitempty"`
	Z                    []byte   `protobuf:"bytes,6,opt,name=z,proto3" json:"z,omitempty"`
	Seed                 []byte   `protobuf:"bytes,7,opt,name=seed,proto3" json:"seed,omitempty"`
	Bids                 []byte   `protobuf:"bytes,8,opt,name=bids,proto3" json:"bids,omitempty"`
	BidPos               uint64   `protobuf:"fixed64,9,opt,name=bid_pos,json=bidPos,proto3" json:"bid_pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateScoreRequest) Reset()         { *m = GenerateScoreRequest{} }
func (m *GenerateScoreRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateScoreRequest) ProtoMessage()    {}
func (*GenerateScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{12}
}

func (m *GenerateScoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateScoreRequest.Unmarshal(m, b)
}
func (m *GenerateScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateScoreRequest.Marshal(b, m, deterministic)
}
func (m *GenerateScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateScoreRequest.Merge(m, src)
}
func (m *GenerateScoreRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateScoreRequest.Size(m)
}
func (m *GenerateScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateScoreRequest proto.InternalMessageInfo

func (m *GenerateScoreRequest) GetD() []byte {
	if m != nil {
		return m.D
	}
	return nil
}

func (m *GenerateScoreRequest) GetK() []byte {
	if m != nil {
		return m.K
	}
	return nil
}

func (m *GenerateScoreRequest) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

func (m *GenerateScoreRequest) GetYInv() []byte {
	if m != nil {
		return m.YInv
	}
	return nil
}

func (m *GenerateScoreRequest) GetQ() []byte {
	if m != nil {
		return m.Q
	}
	return nil
}

func (m *GenerateScoreRequest) GetZ() []byte {
	if m != nil {
		return m.Z
	}
	return nil
}

func (m *GenerateScoreRequest) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

func (m *GenerateScoreRequest) GetBids() []byte {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *GenerateScoreRequest) GetBidPos() uint64 {
	if m != nil {
		return m.BidPos
	}
	return 0
}

type GenerateScoreResponse struct {
	Proof                []byte   `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	Score                []byte   `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
	Z                    []byte   `protobuf:"bytes,3,opt,name=z,proto3" json:"z,omitempty"`
	Bids                 []byte   `protobuf:"bytes,4,opt,name=bids,proto3" json:"bids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateScoreResponse) Reset()         { *m = GenerateScoreResponse{} }
func (m *GenerateScoreResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateScoreResponse) ProtoMessage()    {}
func (*GenerateScoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{13}
}

func (m *GenerateScoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateScoreResponse.Unmarshal(m, b)
}
func (m *GenerateScoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateScoreResponse.Marshal(b, m, deterministic)
}
func (m *GenerateScoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateScoreResponse.Merge(m, src)
}
func (m *GenerateScoreResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateScoreResponse.Size(m)
}
func (m *GenerateScoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateScoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateScoreResponse proto.InternalMessageInfo

func (m *GenerateScoreResponse) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *GenerateScoreResponse) GetScore() []byte {
	if m != nil {
		return m.Score
	}
	return nil
}

func (m *GenerateScoreResponse) GetZ() []byte {
	if m != nil {
		return m.Z
	}
	return nil
}

func (m *GenerateScoreResponse) GetBids() []byte {
	if m != nil {
		return m.Bids
	}
	return nil
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "rusk.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "rusk.EchoResponse")
	proto.RegisterType((*ValidateStateTransitionRequest)(nil), "rusk.ValidateStateTransitionRequest")
	proto.RegisterType((*ContractCall)(nil), "rusk.ContractCall")
	proto.RegisterType((*ValidateStateTransitionResponse)(nil), "rusk.ValidateStateTransitionResponse")
	proto.RegisterType((*ExecuteStateTransitionResponse)(nil), "rusk.ExecuteStateTransitionResponse")
	proto.RegisterType((*ExecuteStateTransitionRequest)(nil), "rusk.ExecuteStateTransitionRequest")
	proto.RegisterType((*GenerateSecretKeyRequest)(nil), "rusk.GenerateSecretKeyRequest")
	proto.RegisterType((*OwnedNotesResponse)(nil), "rusk.OwnedNotesResponse")
	proto.RegisterType((*NewTransactionRequest)(nil), "rusk.NewTransactionRequest")
	proto.RegisterType((*VerifyTransactionResponse)(nil), "rusk.VerifyTransactionResponse")
	proto.RegisterType((*KeysResponse)(nil), "rusk.KeysResponse")
	proto.RegisterType((*GenerateScoreRequest)(nil), "rusk.GenerateScoreRequest")
	proto.RegisterType((*GenerateScoreResponse)(nil), "rusk.GenerateScoreResponse")
}

func init() {
	proto.RegisterFile("rusk.proto", fileDescriptor_211ec4e18343b18f)
}

var fileDescriptor_211ec4e18343b18f = []byte{
	// 934 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x59, 0x6f, 0xdb, 0x46,
	0x10, 0x16, 0x75, 0xd9, 0x19, 0x51, 0x3e, 0x26, 0x76, 0xcd, 0xb2, 0x88, 0x1d, 0x30, 0x2e, 0xe0,
	0xb6, 0x48, 0x0a, 0x38, 0x0f, 0x45, 0x1e, 0x82, 0x00, 0x76, 0x93, 0x26, 0x0e, 0xe0, 0x06, 0xeb,
	0xc0, 0x7d, 0x54, 0x79, 0xac, 0xe0, 0x05, 0x09, 0x52, 0xe6, 0x2e, 0x25, 0x2b, 0x7f, 0xa5, 0xff,
	0xa2, 0x0f, 0xfd, 0x35, 0xfd, 0x31, 0xc5, 0x1e, 0x3c, 0x24, 0x59, 0x4e, 0xdf, 0x76, 0x86, 0xdf,
	0xcc, 0x7e, 0x73, 0x2e, 0x01, 0xf2, 0x82, 0xc7, 0x2f, 0x26, 0x79, 0x26, 0x32, 0xec, 0xca, 0xb3,
	0x3b, 0x18, 0x33, 0x9a, 0x44, 0x5a, 0xe5, 0x42, 0x4c, 0xe7, 0xbc, 0x3c, 0xa7, 0x99, 0xa0, 0xe6,
	0xbc, 0x2b, 0x72, 0x3f, 0xe5, 0x7e, 0x28, 0x58, 0x96, 0x1a, 0xd5, 0x76, 0x98, 0xa5, 0x9c, 0xa6,
	0xbc, 0x30, 0x78, 0x6f, 0x08, 0x83, 0xb7, 0xe1, 0x4d, 0x46, 0xe8, 0x6d, 0x41, 0xb9, 0xf0, 0xb6,
	0xc0, 0xd6, 0x22, 0x9f, 0x48, 0xa0, 0x77, 0x01, 0x87, 0xd7, 0x7e, 0xc2, 0x22, 0x5f, 0xd0, 0x2b,
	0xe1, 0x0b, 0xfa, 0x59, 0x7a, 0x64, 0xd2, 0xa1, 0xb1, 0xc0, 0x13, 0xe8, 0x85, 0x7e, 0x92, 0x70,
	0xc7, 0x7a, 0xda, 0x39, 0x19, 0x9c, 0xe2, 0x0b, 0xc5, 0xf5, 0x3c, 0x4b, 0x45, 0xee, 0x87, 0xe2,
	0xdc, 0x4f, 0x12, 0xa2, 0x01, 0xde, 0x3f, 0x1d, 0xb0, 0x9b, 0x7a, 0x7c, 0x06, 0x6d, 0x71, 0xe7,
	0x58, 0x4f, 0xad, 0x93, 0xc1, 0xe9, 0xae, 0xb6, 0xfb, 0x5c, 0x33, 0x7e, 0xdf, 0x22, 0x6d, 0x71,
	0x87, 0x2f, 0x61, 0x73, 0xc6, 0xc4, 0x4d, 0x94, 0xfb, 0x33, 0xa7, 0xad, 0xa0, 0xfb, 0x1a, 0xfa,
	0x87, 0xd1, 0x1a, 0x22, 0xef, 0x5b, 0xa4, 0x02, 0xe2, 0x8f, 0xd0, 0xe3, 0xc2, 0x8f, 0xa9, 0xd3,
	0x51, 0x16, 0x86, 0xd4, 0x95, 0x54, 0xd5, 0x70, 0x0d, 0xc1, 0x63, 0xe8, 0x04, 0x2c, 0x72, 0xba,
	0x0a, 0xb9, 0xa3, 0x91, 0x67, 0x2c, 0xaa, 0x71, 0xf2, 0xb3, 0xf2, 0x98, 0xf8, 0xfc, 0xc6, 0xe9,
	0x2d, 0x78, 0x94, 0xaa, 0xa6, 0x47, 0x29, 0xe3, 0x2b, 0x80, 0x88, 0x71, 0x91, 0xb3, 0xa0, 0x10,
	0xd4, 0xe9, 0x2b, 0x83, 0x03, 0x6d, 0xf0, 0x6b, 0xa5, 0xaf, 0xad, 0x1a, 0x60, 0x3c, 0x87, 0xad,
	0x32, 0x88, 0x91, 0x8e, 0x60, 0x43, 0x99, 0xbb, 0x8b, 0x31, 0x2f, 0x45, 0x32, 0x9c, 0x35, 0xf5,
	0xf8, 0x1a, 0xec, 0xca, 0x89, 0x0c, 0x6d, 0x53, 0xb9, 0x70, 0x16, 0x5d, 0x2c, 0x84, 0x38, 0x98,
	0xd5, 0xda, 0xb3, 0x6d, 0x18, 0x86, 0xa6, 0x4c, 0x23, 0x59, 0x39, 0xef, 0x4f, 0x38, 0x5a, 0xdb,
	0x04, 0xba, 0x4f, 0xf0, 0x35, 0xec, 0xf0, 0x22, 0x0c, 0x29, 0xe7, 0xe3, 0x22, 0x19, 0x7d, 0xad,
	0x21, 0xb6, 0x6b, 0xec, 0xb9, 0x6a, 0x8d, 0x0b, 0x38, 0x7c, 0x7b, 0x47, 0xc3, 0x62, 0xfd, 0x05,
	0xff, 0xbf, 0xcd, 0x5e, 0xc1, 0x93, 0x75, 0xbe, 0x74, 0xc7, 0x3a, 0xb0, 0x61, 0xee, 0x57, 0xbd,
	0xb7, 0x49, 0x4a, 0xd1, 0x3b, 0x01, 0xe7, 0x37, 0x9a, 0xd2, 0x5c, 0x06, 0x4a, 0xc3, 0x9c, 0x8a,
	0x8f, 0x74, 0x5e, 0x5a, 0xd9, 0x60, 0x05, 0x0a, 0x6f, 0x13, 0x2b, 0xf0, 0xde, 0x00, 0xfe, 0x3e,
	0x4b, 0x69, 0x74, 0x99, 0x09, 0xca, 0x2b, 0x92, 0x3f, 0x40, 0x4f, 0x8e, 0x5f, 0x49, 0xf2, 0xb1,
	0xa9, 0x39, 0x0d, 0xf3, 0xf9, 0x44, 0x68, 0x30, 0xd1, 0x08, 0xef, 0x5f, 0x0b, 0xf6, 0x2f, 0xe9,
	0xac, 0xd1, 0xef, 0xe5, 0x45, 0x47, 0xd0, 0xe6, 0xb1, 0x99, 0x8a, 0x6d, 0xd3, 0x66, 0x15, 0x99,
	0x36, 0x8f, 0xf1, 0x27, 0xe8, 0xb3, 0x74, 0x52, 0x08, 0xee, 0xb4, 0xd7, 0x5f, 0x63, 0x20, 0xf8,
	0x1c, 0x1e, 0xe5, 0x34, 0x64, 0x13, 0x46, 0x53, 0x61, 0xa6, 0xc1, 0x38, 0xfd, 0x54, 0x04, 0x09,
	0x0b, 0xa5, 0xd3, 0x1a, 0x81, 0x7b, 0xd0, 0x9b, 0xfa, 0x49, 0x41, 0xd5, 0x38, 0xf4, 0x89, 0x16,
	0x70, 0x07, 0x3a, 0x63, 0x4a, 0x55, 0xeb, 0xf7, 0x89, 0x3c, 0xe2, 0x21, 0x40, 0x16, 0x8c, 0x0b,
	0x1e, 0xfa, 0x82, 0x46, 0xaa, 0xc5, 0x37, 0x49, 0x43, 0xe3, 0xfd, 0x02, 0xdf, 0x5e, 0xd3, 0x9c,
	0x8d, 0xe7, 0x0b, 0x01, 0x9a, 0x34, 0xb9, 0xb0, 0x39, 0x95, 0x1f, 0x19, 0x8d, 0x4c, 0x05, 0x2a,
	0xd9, 0xbb, 0x04, 0xfb, 0x23, 0x9d, 0xd7, 0x29, 0x7d, 0x02, 0xed, 0x69, 0x99, 0x8d, 0xa1, 0x26,
	0x7e, 0xcd, 0xe8, 0x4c, 0xe5, 0x62, 0x1a, 0xcb, 0x64, 0x4d, 0x62, 0xb3, 0x17, 0x56, 0xe2, 0x6a,
	0x4f, 0x62, 0xef, 0x6f, 0x0b, 0xf6, 0xaa, 0x9a, 0x86, 0x59, 0x4e, 0x1b, 0xf5, 0x8c, 0xca, 0x7a,
	0x46, 0x52, 0xd2, 0x6e, 0x6c, 0x62, 0xc5, 0x52, 0x9a, 0xab, 0x64, 0xd9, 0xc4, 0x9a, 0xe3, 0x63,
	0xe8, 0xcd, 0x47, 0x2c, 0x9d, 0xaa, 0x9c, 0xd8, 0xa4, 0x3b, 0xff, 0x90, 0x4e, 0x25, 0xe4, 0x56,
	0x25, 0xc4, 0x26, 0xd6, 0xad, 0x94, 0xbe, 0xa8, 0x2c, 0xd8, 0xc4, 0xfa, 0x82, 0x08, 0x5d, 0x4e,
	0x69, 0xa4, 0x46, 0xd7, 0x26, 0xea, 0x2c, 0x75, 0x01, 0x8b, 0xb8, 0x9a, 0x45, 0x9b, 0xa8, 0x33,
	0x1e, 0xc0, 0x46, 0xc0, 0xa2, 0xd1, 0x24, 0xe3, 0xce, 0x23, 0x95, 0xda, 0x7e, 0xc0, 0xa2, 0x4f,
	0x19, 0xf7, 0x28, 0xec, 0x2f, 0x71, 0x36, 0xd9, 0xd8, 0x83, 0xde, 0x24, 0xcf, 0xb2, 0xb1, 0x21,
	0xae, 0x05, 0xa9, 0xe5, 0x12, 0x66, 0x02, 0xd0, 0x82, 0xe6, 0xd4, 0x69, 0x70, 0x52, 0xf7, 0x77,
	0xeb, 0xfb, 0x4f, 0xff, 0xea, 0x41, 0x97, 0x14, 0x3c, 0xc6, 0x9f, 0xa1, 0x2b, 0xb7, 0x3e, 0x9a,
	0x25, 0xdc, 0x78, 0x10, 0x5c, 0x6c, 0xaa, 0xcc, 0xa3, 0xd0, 0xc2, 0x1b, 0x38, 0x58, 0xb3, 0x11,
	0xf0, 0xd8, 0x14, 0xe9, 0xc1, 0x57, 0xc3, 0xfd, 0xfe, 0x2b, 0xa8, 0xea, 0x26, 0x0a, 0xdf, 0xdc,
	0x3f, 0xcd, 0xf8, 0xcc, 0x30, 0x7b, 0x68, 0xd6, 0xdd, 0xe3, 0x87, 0x41, 0xd5, 0x35, 0x17, 0x30,
	0x5c, 0xc8, 0x38, 0x9a, 0x85, 0x7b, 0x5f, 0xeb, 0xb8, 0xdf, 0xdd, 0xfb, 0xad, 0xf2, 0xf5, 0x0e,
	0x76, 0x57, 0xb6, 0x08, 0x1e, 0x2e, 0xd9, 0x2c, 0xad, 0x17, 0x77, 0x79, 0xd2, 0xbd, 0x16, 0x3e,
	0x87, 0xae, 0x1c, 0x05, 0x5c, 0xfe, 0x54, 0xd6, 0xa4, 0x39, 0x27, 0x5e, 0x0b, 0xdf, 0x00, 0xbe,
	0x2b, 0x92, 0xe4, 0x2a, 0xf4, 0xd3, 0x7a, 0x35, 0xe1, 0xe2, 0xcc, 0xb8, 0xe6, 0x11, 0x58, 0xdd,
	0x5d, 0x5e, 0x0b, 0xcf, 0x60, 0x6b, 0x71, 0x23, 0xa1, 0x09, 0xf4, 0xde, 0x3d, 0xe5, 0xae, 0xbe,
	0xd8, 0x5e, 0x0b, 0x3f, 0xc0, 0xee, 0xca, 0xdc, 0xe3, 0x2a, 0xd2, 0x3d, 0x32, 0xb4, 0xd6, 0xed,
	0x08, 0xaf, 0x15, 0xf4, 0xd5, 0x0f, 0xca, 0xcb, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xf6,
	0x5e, 0xce, 0xfd, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RuskClient is the client API for Rusk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuskClient interface {
	// Simple echo request
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Validate a set of contract calls, returning false if at least one of the
	// listed transactions is inconsistent
	ValidateStateTransition(ctx context.Context, in *ValidateStateTransitionRequest, opts ...grpc.CallOption) (*ValidateStateTransitionResponse, error)
	// Execute a set of contract calls, resulting in a mutation of the contract
	// storage.
	ExecuteStateTransition(ctx context.Context, in *ExecuteStateTransitionRequest, opts ...grpc.CallOption) (*ExecuteStateTransitionResponse, error)
	// Generate a proof of blind bid, and a score.
	GenerateScore(ctx context.Context, in *GenerateScoreRequest, opts ...grpc.CallOption) (*GenerateScoreResponse, error)
	// Phoenix stuff
	GenerateSecretKey(ctx context.Context, in *GenerateSecretKeyRequest, opts ...grpc.CallOption) (*SecretKey, error)
	Keys(ctx context.Context, in *SecretKey, opts ...grpc.CallOption) (*KeysResponse, error)
	FullScanOwnedNotes(ctx context.Context, in *ViewKey, opts ...grpc.CallOption) (*OwnedNotesResponse, error)
	NewTransaction(ctx context.Context, in *NewTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	VerifyTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*VerifyTransactionResponse, error)
}

type ruskClient struct {
	cc grpc.ClientConnInterface
}

func NewRuskClient(cc grpc.ClientConnInterface) RuskClient {
	return &ruskClient{cc}
}

func (c *ruskClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) ValidateStateTransition(ctx context.Context, in *ValidateStateTransitionRequest, opts ...grpc.CallOption) (*ValidateStateTransitionResponse, error) {
	out := new(ValidateStateTransitionResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/ValidateStateTransition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) ExecuteStateTransition(ctx context.Context, in *ExecuteStateTransitionRequest, opts ...grpc.CallOption) (*ExecuteStateTransitionResponse, error) {
	out := new(ExecuteStateTransitionResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/ExecuteStateTransition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) GenerateScore(ctx context.Context, in *GenerateScoreRequest, opts ...grpc.CallOption) (*GenerateScoreResponse, error) {
	out := new(GenerateScoreResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/GenerateScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) GenerateSecretKey(ctx context.Context, in *GenerateSecretKeyRequest, opts ...grpc.CallOption) (*SecretKey, error) {
	out := new(SecretKey)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/GenerateSecretKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) Keys(ctx context.Context, in *SecretKey, opts ...grpc.CallOption) (*KeysResponse, error) {
	out := new(KeysResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/Keys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) FullScanOwnedNotes(ctx context.Context, in *ViewKey, opts ...grpc.CallOption) (*OwnedNotesResponse, error) {
	out := new(OwnedNotesResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/FullScanOwnedNotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) NewTransaction(ctx context.Context, in *NewTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/NewTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) VerifyTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*VerifyTransactionResponse, error) {
	out := new(VerifyTransactionResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/VerifyTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuskServer is the server API for Rusk service.
type RuskServer interface {
	// Simple echo request
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// Validate a set of contract calls, returning false if at least one of the
	// listed transactions is inconsistent
	ValidateStateTransition(context.Context, *ValidateStateTransitionRequest) (*ValidateStateTransitionResponse, error)
	// Execute a set of contract calls, resulting in a mutation of the contract
	// storage.
	ExecuteStateTransition(context.Context, *ExecuteStateTransitionRequest) (*ExecuteStateTransitionResponse, error)
	// Generate a proof of blind bid, and a score.
	GenerateScore(context.Context, *GenerateScoreRequest) (*GenerateScoreResponse, error)
	// Phoenix stuff
	GenerateSecretKey(context.Context, *GenerateSecretKeyRequest) (*SecretKey, error)
	Keys(context.Context, *SecretKey) (*KeysResponse, error)
	FullScanOwnedNotes(context.Context, *ViewKey) (*OwnedNotesResponse, error)
	NewTransaction(context.Context, *NewTransactionRequest) (*Transaction, error)
	VerifyTransaction(context.Context, *Transaction) (*VerifyTransactionResponse, error)
}

// UnimplementedRuskServer can be embedded to have forward compatible implementations.
type UnimplementedRuskServer struct {
}

func (*UnimplementedRuskServer) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (*UnimplementedRuskServer) ValidateStateTransition(ctx context.Context, req *ValidateStateTransitionRequest) (*ValidateStateTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateStateTransition not implemented")
}
func (*UnimplementedRuskServer) ExecuteStateTransition(ctx context.Context, req *ExecuteStateTransitionRequest) (*ExecuteStateTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteStateTransition not implemented")
}
func (*UnimplementedRuskServer) GenerateScore(ctx context.Context, req *GenerateScoreRequest) (*GenerateScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateScore not implemented")
}
func (*UnimplementedRuskServer) GenerateSecretKey(ctx context.Context, req *GenerateSecretKeyRequest) (*SecretKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSecretKey not implemented")
}
func (*UnimplementedRuskServer) Keys(ctx context.Context, req *SecretKey) (*KeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Keys not implemented")
}
func (*UnimplementedRuskServer) FullScanOwnedNotes(ctx context.Context, req *ViewKey) (*OwnedNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FullScanOwnedNotes not implemented")
}
func (*UnimplementedRuskServer) NewTransaction(ctx context.Context, req *NewTransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTransaction not implemented")
}
func (*UnimplementedRuskServer) VerifyTransaction(ctx context.Context, req *Transaction) (*VerifyTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTransaction not implemented")
}

func RegisterRuskServer(s *grpc.Server, srv RuskServer) {
	s.RegisterService(&_Rusk_serviceDesc, srv)
}

func _Rusk_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_ValidateStateTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateStateTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).ValidateStateTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/ValidateStateTransition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).ValidateStateTransition(ctx, req.(*ValidateStateTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_ExecuteStateTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteStateTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).ExecuteStateTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/ExecuteStateTransition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).ExecuteStateTransition(ctx, req.(*ExecuteStateTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_GenerateScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).GenerateScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/GenerateScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).GenerateScore(ctx, req.(*GenerateScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_GenerateSecretKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSecretKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).GenerateSecretKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/GenerateSecretKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).GenerateSecretKey(ctx, req.(*GenerateSecretKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_Keys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Keys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/Keys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Keys(ctx, req.(*SecretKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_FullScanOwnedNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).FullScanOwnedNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/FullScanOwnedNotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).FullScanOwnedNotes(ctx, req.(*ViewKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_NewTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).NewTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/NewTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).NewTransaction(ctx, req.(*NewTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_VerifyTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).VerifyTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/VerifyTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).VerifyTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rusk_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rusk.Rusk",
	HandlerType: (*RuskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Rusk_Echo_Handler,
		},
		{
			MethodName: "ValidateStateTransition",
			Handler:    _Rusk_ValidateStateTransition_Handler,
		},
		{
			MethodName: "ExecuteStateTransition",
			Handler:    _Rusk_ExecuteStateTransition_Handler,
		},
		{
			MethodName: "GenerateScore",
			Handler:    _Rusk_GenerateScore_Handler,
		},
		{
			MethodName: "GenerateSecretKey",
			Handler:    _Rusk_GenerateSecretKey_Handler,
		},
		{
			MethodName: "Keys",
			Handler:    _Rusk_Keys_Handler,
		},
		{
			MethodName: "FullScanOwnedNotes",
			Handler:    _Rusk_FullScanOwnedNotes_Handler,
		},
		{
			MethodName: "NewTransaction",
			Handler:    _Rusk_NewTransaction_Handler,
		},
		{
			MethodName: "VerifyTransaction",
			Handler:    _Rusk_VerifyTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rusk.proto",
}
