// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rusk.proto

package rusk

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

type EchoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{1}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

type ValidateStateTransitionRequest struct {
	// List of transactions to be validated
	Txs                  []*Transaction `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ValidateStateTransitionRequest) Reset()         { *m = ValidateStateTransitionRequest{} }
func (m *ValidateStateTransitionRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateStateTransitionRequest) ProtoMessage()    {}
func (*ValidateStateTransitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{2}
}

func (m *ValidateStateTransitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateStateTransitionRequest.Unmarshal(m, b)
}
func (m *ValidateStateTransitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateStateTransitionRequest.Marshal(b, m, deterministic)
}
func (m *ValidateStateTransitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateStateTransitionRequest.Merge(m, src)
}
func (m *ValidateStateTransitionRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateStateTransitionRequest.Size(m)
}
func (m *ValidateStateTransitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateStateTransitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateStateTransitionRequest proto.InternalMessageInfo

func (m *ValidateStateTransitionRequest) GetTxs() []*Transaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

type ValidateStateTransitionResponse struct {
	// Status of the state transition
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateStateTransitionResponse) Reset()         { *m = ValidateStateTransitionResponse{} }
func (m *ValidateStateTransitionResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateStateTransitionResponse) ProtoMessage()    {}
func (*ValidateStateTransitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{3}
}

func (m *ValidateStateTransitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateStateTransitionResponse.Unmarshal(m, b)
}
func (m *ValidateStateTransitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateStateTransitionResponse.Marshal(b, m, deterministic)
}
func (m *ValidateStateTransitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateStateTransitionResponse.Merge(m, src)
}
func (m *ValidateStateTransitionResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateStateTransitionResponse.Size(m)
}
func (m *ValidateStateTransitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateStateTransitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateStateTransitionResponse proto.InternalMessageInfo

func (m *ValidateStateTransitionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GenerateSecretKeyRequest struct {
	B                    []byte   `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateSecretKeyRequest) Reset()         { *m = GenerateSecretKeyRequest{} }
func (m *GenerateSecretKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateSecretKeyRequest) ProtoMessage()    {}
func (*GenerateSecretKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{4}
}

func (m *GenerateSecretKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateSecretKeyRequest.Unmarshal(m, b)
}
func (m *GenerateSecretKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateSecretKeyRequest.Marshal(b, m, deterministic)
}
func (m *GenerateSecretKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateSecretKeyRequest.Merge(m, src)
}
func (m *GenerateSecretKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateSecretKeyRequest.Size(m)
}
func (m *GenerateSecretKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateSecretKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateSecretKeyRequest proto.InternalMessageInfo

func (m *GenerateSecretKeyRequest) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

// TODO: ask what the below four structures are for
type FetchNoteRequest struct {
	Pos                  uint64   `protobuf:"fixed64,1,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchNoteRequest) Reset()         { *m = FetchNoteRequest{} }
func (m *FetchNoteRequest) String() string { return proto.CompactTextString(m) }
func (*FetchNoteRequest) ProtoMessage()    {}
func (*FetchNoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{5}
}

func (m *FetchNoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchNoteRequest.Unmarshal(m, b)
}
func (m *FetchNoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchNoteRequest.Marshal(b, m, deterministic)
}
func (m *FetchNoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchNoteRequest.Merge(m, src)
}
func (m *FetchNoteRequest) XXX_Size() int {
	return xxx_messageInfo_FetchNoteRequest.Size(m)
}
func (m *FetchNoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchNoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchNoteRequest proto.InternalMessageInfo

func (m *FetchNoteRequest) GetPos() uint64 {
	if m != nil {
		return m.Pos
	}
	return 0
}

type DecryptNoteRequest struct {
	Note                 *Note    `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	Vk                   *ViewKey `protobuf:"bytes,2,opt,name=vk,proto3" json:"vk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptNoteRequest) Reset()         { *m = DecryptNoteRequest{} }
func (m *DecryptNoteRequest) String() string { return proto.CompactTextString(m) }
func (*DecryptNoteRequest) ProtoMessage()    {}
func (*DecryptNoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{6}
}

func (m *DecryptNoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptNoteRequest.Unmarshal(m, b)
}
func (m *DecryptNoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptNoteRequest.Marshal(b, m, deterministic)
}
func (m *DecryptNoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptNoteRequest.Merge(m, src)
}
func (m *DecryptNoteRequest) XXX_Size() int {
	return xxx_messageInfo_DecryptNoteRequest.Size(m)
}
func (m *DecryptNoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptNoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptNoteRequest proto.InternalMessageInfo

func (m *DecryptNoteRequest) GetNote() *Note {
	if m != nil {
		return m.Note
	}
	return nil
}

func (m *DecryptNoteRequest) GetVk() *ViewKey {
	if m != nil {
		return m.Vk
	}
	return nil
}

type OwnedNotesRequest struct {
	Vk                   *ViewKey `protobuf:"bytes,1,opt,name=vk,proto3" json:"vk,omitempty"`
	Notes                []*Note  `protobuf:"bytes,2,rep,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnedNotesRequest) Reset()         { *m = OwnedNotesRequest{} }
func (m *OwnedNotesRequest) String() string { return proto.CompactTextString(m) }
func (*OwnedNotesRequest) ProtoMessage()    {}
func (*OwnedNotesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{7}
}

func (m *OwnedNotesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnedNotesRequest.Unmarshal(m, b)
}
func (m *OwnedNotesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnedNotesRequest.Marshal(b, m, deterministic)
}
func (m *OwnedNotesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnedNotesRequest.Merge(m, src)
}
func (m *OwnedNotesRequest) XXX_Size() int {
	return xxx_messageInfo_OwnedNotesRequest.Size(m)
}
func (m *OwnedNotesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnedNotesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OwnedNotesRequest proto.InternalMessageInfo

func (m *OwnedNotesRequest) GetVk() *ViewKey {
	if m != nil {
		return m.Vk
	}
	return nil
}

func (m *OwnedNotesRequest) GetNotes() []*Note {
	if m != nil {
		return m.Notes
	}
	return nil
}

type OwnedNotesResponse struct {
	Notes                []*DecryptedNote `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OwnedNotesResponse) Reset()         { *m = OwnedNotesResponse{} }
func (m *OwnedNotesResponse) String() string { return proto.CompactTextString(m) }
func (*OwnedNotesResponse) ProtoMessage()    {}
func (*OwnedNotesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{8}
}

func (m *OwnedNotesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnedNotesResponse.Unmarshal(m, b)
}
func (m *OwnedNotesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnedNotesResponse.Marshal(b, m, deterministic)
}
func (m *OwnedNotesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnedNotesResponse.Merge(m, src)
}
func (m *OwnedNotesResponse) XXX_Size() int {
	return xxx_messageInfo_OwnedNotesResponse.Size(m)
}
func (m *OwnedNotesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnedNotesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OwnedNotesResponse proto.InternalMessageInfo

func (m *OwnedNotesResponse) GetNotes() []*DecryptedNote {
	if m != nil {
		return m.Notes
	}
	return nil
}

// Call from CLI directly
type NewTransactionRequest struct {
	Sk                   *SecretKey       `protobuf:"bytes,1,opt,name=sk,proto3" json:"sk,omitempty"`
	Inputs               []*DecryptedNote `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Recipient            *PublicKey       `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Value                uint64           `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Fee                  uint64           `protobuf:"fixed64,5,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NewTransactionRequest) Reset()         { *m = NewTransactionRequest{} }
func (m *NewTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*NewTransactionRequest) ProtoMessage()    {}
func (*NewTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{9}
}

func (m *NewTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTransactionRequest.Unmarshal(m, b)
}
func (m *NewTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTransactionRequest.Marshal(b, m, deterministic)
}
func (m *NewTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransactionRequest.Merge(m, src)
}
func (m *NewTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_NewTransactionRequest.Size(m)
}
func (m *NewTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransactionRequest proto.InternalMessageInfo

func (m *NewTransactionRequest) GetSk() *SecretKey {
	if m != nil {
		return m.Sk
	}
	return nil
}

func (m *NewTransactionRequest) GetInputs() []*DecryptedNote {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *NewTransactionRequest) GetRecipient() *PublicKey {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *NewTransactionRequest) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NewTransactionRequest) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type VerifyTransactionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTransactionResponse) Reset()         { *m = VerifyTransactionResponse{} }
func (m *VerifyTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyTransactionResponse) ProtoMessage()    {}
func (*VerifyTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{10}
}

func (m *VerifyTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTransactionResponse.Unmarshal(m, b)
}
func (m *VerifyTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTransactionResponse.Marshal(b, m, deterministic)
}
func (m *VerifyTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTransactionResponse.Merge(m, src)
}
func (m *VerifyTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyTransactionResponse.Size(m)
}
func (m *VerifyTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTransactionResponse proto.InternalMessageInfo

type VerifyTransactionRootRequest struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Root                 *Scalar      `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VerifyTransactionRootRequest) Reset()         { *m = VerifyTransactionRootRequest{} }
func (m *VerifyTransactionRootRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyTransactionRootRequest) ProtoMessage()    {}
func (*VerifyTransactionRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{11}
}

func (m *VerifyTransactionRootRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTransactionRootRequest.Unmarshal(m, b)
}
func (m *VerifyTransactionRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTransactionRootRequest.Marshal(b, m, deterministic)
}
func (m *VerifyTransactionRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTransactionRootRequest.Merge(m, src)
}
func (m *VerifyTransactionRootRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyTransactionRootRequest.Size(m)
}
func (m *VerifyTransactionRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTransactionRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTransactionRootRequest proto.InternalMessageInfo

func (m *VerifyTransactionRootRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *VerifyTransactionRootRequest) GetRoot() *Scalar {
	if m != nil {
		return m.Root
	}
	return nil
}

type VerifyTransactionRootResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTransactionRootResponse) Reset()         { *m = VerifyTransactionRootResponse{} }
func (m *VerifyTransactionRootResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyTransactionRootResponse) ProtoMessage()    {}
func (*VerifyTransactionRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{12}
}

func (m *VerifyTransactionRootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTransactionRootResponse.Unmarshal(m, b)
}
func (m *VerifyTransactionRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTransactionRootResponse.Marshal(b, m, deterministic)
}
func (m *VerifyTransactionRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTransactionRootResponse.Merge(m, src)
}
func (m *VerifyTransactionRootResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyTransactionRootResponse.Size(m)
}
func (m *VerifyTransactionRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTransactionRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTransactionRootResponse proto.InternalMessageInfo

type KeysResponse struct {
	Vk                   *ViewKey   `protobuf:"bytes,1,opt,name=vk,proto3" json:"vk,omitempty"`
	Pk                   *PublicKey `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *KeysResponse) Reset()         { *m = KeysResponse{} }
func (m *KeysResponse) String() string { return proto.CompactTextString(m) }
func (*KeysResponse) ProtoMessage()    {}
func (*KeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{13}
}

func (m *KeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysResponse.Unmarshal(m, b)
}
func (m *KeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysResponse.Marshal(b, m, deterministic)
}
func (m *KeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysResponse.Merge(m, src)
}
func (m *KeysResponse) XXX_Size() int {
	return xxx_messageInfo_KeysResponse.Size(m)
}
func (m *KeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeysResponse proto.InternalMessageInfo

func (m *KeysResponse) GetVk() *ViewKey {
	if m != nil {
		return m.Vk
	}
	return nil
}

func (m *KeysResponse) GetPk() *PublicKey {
	if m != nil {
		return m.Pk
	}
	return nil
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "rusk.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "rusk.EchoResponse")
	proto.RegisterType((*ValidateStateTransitionRequest)(nil), "rusk.ValidateStateTransitionRequest")
	proto.RegisterType((*ValidateStateTransitionResponse)(nil), "rusk.ValidateStateTransitionResponse")
	proto.RegisterType((*GenerateSecretKeyRequest)(nil), "rusk.GenerateSecretKeyRequest")
	proto.RegisterType((*FetchNoteRequest)(nil), "rusk.FetchNoteRequest")
	proto.RegisterType((*DecryptNoteRequest)(nil), "rusk.DecryptNoteRequest")
	proto.RegisterType((*OwnedNotesRequest)(nil), "rusk.OwnedNotesRequest")
	proto.RegisterType((*OwnedNotesResponse)(nil), "rusk.OwnedNotesResponse")
	proto.RegisterType((*NewTransactionRequest)(nil), "rusk.NewTransactionRequest")
	proto.RegisterType((*VerifyTransactionResponse)(nil), "rusk.VerifyTransactionResponse")
	proto.RegisterType((*VerifyTransactionRootRequest)(nil), "rusk.VerifyTransactionRootRequest")
	proto.RegisterType((*VerifyTransactionRootResponse)(nil), "rusk.VerifyTransactionRootResponse")
	proto.RegisterType((*KeysResponse)(nil), "rusk.KeysResponse")
}

func init() {
	proto.RegisterFile("rusk.proto", fileDescriptor_211ec4e18343b18f)
}

var fileDescriptor_211ec4e18343b18f = []byte{
	// 657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdd, 0x4e, 0xdb, 0x4c,
	0x10, 0x75, 0x1c, 0x87, 0xef, 0x63, 0x12, 0x28, 0x99, 0xfe, 0xe0, 0x9a, 0x42, 0xd0, 0x96, 0x4a,
	0x54, 0x15, 0x54, 0x85, 0xcb, 0x4a, 0x45, 0xad, 0x0a, 0x55, 0x85, 0x44, 0x2b, 0x83, 0xb8, 0x77,
	0xcc, 0x44, 0x58, 0xb6, 0x6c, 0xd7, 0xbb, 0x86, 0xe6, 0x65, 0xfa, 0x24, 0x7d, 0xb8, 0x6a, 0xbd,
	0x6b, 0xb2, 0xc1, 0x31, 0xdc, 0xad, 0x77, 0xce, 0x9c, 0xf9, 0xd9, 0x73, 0x12, 0x80, 0xa2, 0xe4,
	0xf1, 0x7e, 0x5e, 0x64, 0x22, 0x43, 0x47, 0x9e, 0xbd, 0xfe, 0x24, 0xa2, 0xe4, 0x4a, 0x5d, 0x79,
	0x10, 0xd3, 0x94, 0xd7, 0xe7, 0x34, 0x13, 0xa4, 0xcf, 0x43, 0x51, 0x04, 0x29, 0x0f, 0x42, 0x11,
	0x65, 0xa9, 0xba, 0x62, 0x2b, 0xd0, 0x3f, 0x0e, 0xaf, 0x33, 0x9f, 0x7e, 0x95, 0xc4, 0x05, 0x5b,
	0x85, 0x81, 0xfa, 0xe4, 0x79, 0x96, 0x72, 0x62, 0xc7, 0xb0, 0x75, 0x19, 0x24, 0xd1, 0x55, 0x20,
	0xe8, 0x5c, 0x04, 0x82, 0x2e, 0x24, 0x41, 0x24, 0xf3, 0x75, 0x06, 0xbe, 0x86, 0xae, 0xf8, 0xcd,
	0xdd, 0xce, 0x76, 0x77, 0xb7, 0x7f, 0x30, 0xdc, 0xaf, 0x1a, 0xbb, 0x98, 0x95, 0xf1, 0x65, 0x94,
	0x7d, 0x84, 0x51, 0x2b, 0x8d, 0xaa, 0x84, 0x2e, 0xfc, 0xc7, 0xcb, 0x30, 0x24, 0x2e, 0xb9, 0x3a,
	0xbb, 0xff, 0xfb, 0xf5, 0x27, 0xdb, 0x05, 0xf7, 0x1b, 0xa5, 0x54, 0xc8, 0x64, 0x0a, 0x0b, 0x12,
	0xa7, 0x34, 0xad, 0xab, 0x0f, 0xa0, 0x33, 0xae, 0xf0, 0x03, 0xbf, 0x33, 0x66, 0x3b, 0xb0, 0x76,
	0x42, 0x22, 0xbc, 0x3e, 0xcb, 0x04, 0xd5, 0x88, 0x35, 0xe8, 0xe6, 0x99, 0xe2, 0x5c, 0xf2, 0xe5,
	0x91, 0x9d, 0x03, 0x7e, 0xa5, 0xb0, 0x98, 0xe6, 0xc2, 0xc4, 0x6d, 0x81, 0x23, 0x37, 0x55, 0x01,
	0xfb, 0x07, 0xa0, 0x06, 0xa9, 0x00, 0xd5, 0x3d, 0x6e, 0x82, 0x7d, 0x13, 0xbb, 0x76, 0x15, 0x5d,
	0x51, 0xd1, 0xcb, 0x88, 0x6e, 0x65, 0x2f, 0xf6, 0x4d, 0xcc, 0x2e, 0x60, 0xf8, 0xe3, 0x36, 0xa5,
	0x2b, 0x99, 0xc1, 0x6b, 0x4e, 0x95, 0xd3, 0x69, 0xc9, 0xc1, 0x6d, 0xe8, 0x49, 0x6a, 0xee, 0xda,
	0xd5, 0xf2, 0xcc, 0x9a, 0x2a, 0xc0, 0x8e, 0x00, 0x4d, 0x56, 0xbd, 0xaa, 0xb7, 0x75, 0x9e, 0x5a,
	0xfa, 0x53, 0x95, 0xa7, 0x67, 0x52, 0xe0, 0x9a, 0xe0, 0x6f, 0x07, 0x9e, 0x9f, 0xd1, 0xad, 0xf9,
	0x20, 0xba, 0xb7, 0x11, 0xd8, 0xbc, 0xee, 0xed, 0x89, 0x62, 0x98, 0x6d, 0xd7, 0xe6, 0x31, 0xbe,
	0x83, 0xa5, 0x28, 0xcd, 0x4b, 0x51, 0xb7, 0xb7, 0xb0, 0x8c, 0x86, 0xe0, 0x1e, 0x2c, 0x17, 0x14,
	0x46, 0x79, 0x44, 0xa9, 0x70, 0xbb, 0x26, 0xe9, 0xcf, 0x72, 0x9c, 0x44, 0xa1, 0x24, 0x9d, 0x21,
	0xf0, 0x19, 0xf4, 0x6e, 0x82, 0xa4, 0x24, 0xd7, 0xa9, 0x9e, 0x45, 0x7d, 0xc8, 0xa7, 0x9a, 0x10,
	0xb9, 0x3d, 0xf5, 0x54, 0x13, 0x22, 0xb6, 0x01, 0x2f, 0x2f, 0xa9, 0x88, 0x26, 0xd3, 0xb9, 0x01,
	0xb4, 0x36, 0x4b, 0x78, 0xd5, 0x0c, 0x66, 0x99, 0xa8, 0x27, 0x3c, 0x84, 0xbe, 0xa1, 0x77, 0x3d,
	0xea, 0x02, 0x85, 0x9a, 0x28, 0xdc, 0x06, 0xa7, 0xc8, 0x32, 0xa1, 0x1f, 0x7a, 0xa0, 0x17, 0x13,
	0x06, 0x49, 0x50, 0xf8, 0x55, 0x84, 0x8d, 0x60, 0xb3, 0xa5, 0xac, 0xee, 0xeb, 0x0c, 0x06, 0xa7,
	0x34, 0x9d, 0x3d, 0xd7, 0x23, 0x2a, 0x18, 0x81, 0x9d, 0xd7, 0xc2, 0x6a, 0xec, 0xcc, 0xce, 0xe3,
	0x83, 0x3f, 0x3d, 0x70, 0xfc, 0x92, 0xc7, 0xf8, 0x1e, 0x1c, 0x69, 0x4e, 0xd4, 0x33, 0x18, 0xbe,
	0xf5, 0xd0, 0xbc, 0xd2, 0x7d, 0x58, 0x78, 0x0d, 0xeb, 0x2d, 0xb6, 0xc3, 0x1d, 0xdd, 0xc8, 0x83,
	0xe6, 0xf6, 0xde, 0x3c, 0x82, 0xba, 0xab, 0x74, 0x02, 0xc3, 0x86, 0x47, 0x71, 0x4b, 0x65, 0xb7,
	0x99, 0xd7, 0xbb, 0x2f, 0x3b, 0x66, 0xe1, 0x1e, 0x38, 0x72, 0x77, 0x78, 0x3f, 0x54, 0x0f, 0x68,
	0x2e, 0x96, 0x59, 0xf8, 0x01, 0x96, 0xef, 0x0c, 0x8f, 0x2f, 0x14, 0xe4, 0xfe, 0x2f, 0x80, 0x67,
	0xf8, 0x8a, 0x59, 0xf8, 0x09, 0xfa, 0x86, 0xfb, 0xd1, 0x9d, 0x53, 0xb5, 0x99, 0xb6, 0x48, 0xef,
	0xcc, 0xc2, 0xcf, 0x00, 0x33, 0x4b, 0xe2, 0xba, 0x02, 0x35, 0xac, 0xef, 0xb9, 0xcd, 0xc0, 0x5d,
	0xd7, 0x47, 0x80, 0x27, 0x65, 0x92, 0x9c, 0x87, 0x41, 0x6a, 0x50, 0xcd, 0x4b, 0xe3, 0x41, 0x82,
	0x2f, 0xb0, 0x3a, 0x6f, 0x6a, 0xdc, 0xd0, 0x33, 0x2e, 0xb2, 0xba, 0xd7, 0xd4, 0x3c, 0xb3, 0xf0,
	0x3b, 0x0c, 0x1b, 0x32, 0xc6, 0x26, 0xd2, 0x1b, 0xe9, 0xb6, 0x5a, 0x6d, 0x68, 0x8d, 0x97, 0xaa,
	0xbf, 0x92, 0xc3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x37, 0x8d, 0xd7, 0x96, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RuskClient is the client API for Rusk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuskClient interface {
	// Simple echo request
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Validate a set of transactions, returning false if at least one of the
	// listed transactions is inconsistent
	ValidateStateTransition(ctx context.Context, in *ValidateStateTransitionRequest, opts ...grpc.CallOption) (*ValidateStateTransitionResponse, error)
	// Phoenix stuff
	GenerateSecretKey(ctx context.Context, in *GenerateSecretKeyRequest, opts ...grpc.CallOption) (*SecretKey, error)
	Keys(ctx context.Context, in *SecretKey, opts ...grpc.CallOption) (*KeysResponse, error)
	FetchNote(ctx context.Context, in *FetchNoteRequest, opts ...grpc.CallOption) (*Note, error)
	DecryptNote(ctx context.Context, in *DecryptNoteRequest, opts ...grpc.CallOption) (*DecryptedNote, error)
	OwnedNotes(ctx context.Context, in *OwnedNotesRequest, opts ...grpc.CallOption) (*OwnedNotesResponse, error)
	FullScanOwnedNotes(ctx context.Context, in *ViewKey, opts ...grpc.CallOption) (*OwnedNotesResponse, error)
	NewTransaction(ctx context.Context, in *NewTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	VerifyTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*VerifyTransactionResponse, error)
}

type ruskClient struct {
	cc grpc.ClientConnInterface
}

func NewRuskClient(cc grpc.ClientConnInterface) RuskClient {
	return &ruskClient{cc}
}

func (c *ruskClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) ValidateStateTransition(ctx context.Context, in *ValidateStateTransitionRequest, opts ...grpc.CallOption) (*ValidateStateTransitionResponse, error) {
	out := new(ValidateStateTransitionResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/ValidateStateTransition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) GenerateSecretKey(ctx context.Context, in *GenerateSecretKeyRequest, opts ...grpc.CallOption) (*SecretKey, error) {
	out := new(SecretKey)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/GenerateSecretKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) Keys(ctx context.Context, in *SecretKey, opts ...grpc.CallOption) (*KeysResponse, error) {
	out := new(KeysResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/Keys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) FetchNote(ctx context.Context, in *FetchNoteRequest, opts ...grpc.CallOption) (*Note, error) {
	out := new(Note)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/FetchNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) DecryptNote(ctx context.Context, in *DecryptNoteRequest, opts ...grpc.CallOption) (*DecryptedNote, error) {
	out := new(DecryptedNote)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/DecryptNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) OwnedNotes(ctx context.Context, in *OwnedNotesRequest, opts ...grpc.CallOption) (*OwnedNotesResponse, error) {
	out := new(OwnedNotesResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/OwnedNotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) FullScanOwnedNotes(ctx context.Context, in *ViewKey, opts ...grpc.CallOption) (*OwnedNotesResponse, error) {
	out := new(OwnedNotesResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/FullScanOwnedNotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) NewTransaction(ctx context.Context, in *NewTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/NewTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) VerifyTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*VerifyTransactionResponse, error) {
	out := new(VerifyTransactionResponse)
	err := c.cc.Invoke(ctx, "/rusk.Rusk/VerifyTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuskServer is the server API for Rusk service.
type RuskServer interface {
	// Simple echo request
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// Validate a set of transactions, returning false if at least one of the
	// listed transactions is inconsistent
	ValidateStateTransition(context.Context, *ValidateStateTransitionRequest) (*ValidateStateTransitionResponse, error)
	// Phoenix stuff
	GenerateSecretKey(context.Context, *GenerateSecretKeyRequest) (*SecretKey, error)
	Keys(context.Context, *SecretKey) (*KeysResponse, error)
	FetchNote(context.Context, *FetchNoteRequest) (*Note, error)
	DecryptNote(context.Context, *DecryptNoteRequest) (*DecryptedNote, error)
	OwnedNotes(context.Context, *OwnedNotesRequest) (*OwnedNotesResponse, error)
	FullScanOwnedNotes(context.Context, *ViewKey) (*OwnedNotesResponse, error)
	NewTransaction(context.Context, *NewTransactionRequest) (*Transaction, error)
	VerifyTransaction(context.Context, *Transaction) (*VerifyTransactionResponse, error)
}

// UnimplementedRuskServer can be embedded to have forward compatible implementations.
type UnimplementedRuskServer struct {
}

func (*UnimplementedRuskServer) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (*UnimplementedRuskServer) ValidateStateTransition(ctx context.Context, req *ValidateStateTransitionRequest) (*ValidateStateTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateStateTransition not implemented")
}
func (*UnimplementedRuskServer) GenerateSecretKey(ctx context.Context, req *GenerateSecretKeyRequest) (*SecretKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSecretKey not implemented")
}
func (*UnimplementedRuskServer) Keys(ctx context.Context, req *SecretKey) (*KeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Keys not implemented")
}
func (*UnimplementedRuskServer) FetchNote(ctx context.Context, req *FetchNoteRequest) (*Note, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchNote not implemented")
}
func (*UnimplementedRuskServer) DecryptNote(ctx context.Context, req *DecryptNoteRequest) (*DecryptedNote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptNote not implemented")
}
func (*UnimplementedRuskServer) OwnedNotes(ctx context.Context, req *OwnedNotesRequest) (*OwnedNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OwnedNotes not implemented")
}
func (*UnimplementedRuskServer) FullScanOwnedNotes(ctx context.Context, req *ViewKey) (*OwnedNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FullScanOwnedNotes not implemented")
}
func (*UnimplementedRuskServer) NewTransaction(ctx context.Context, req *NewTransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTransaction not implemented")
}
func (*UnimplementedRuskServer) VerifyTransaction(ctx context.Context, req *Transaction) (*VerifyTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTransaction not implemented")
}

func RegisterRuskServer(s *grpc.Server, srv RuskServer) {
	s.RegisterService(&_Rusk_serviceDesc, srv)
}

func _Rusk_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_ValidateStateTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateStateTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).ValidateStateTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/ValidateStateTransition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).ValidateStateTransition(ctx, req.(*ValidateStateTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_GenerateSecretKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSecretKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).GenerateSecretKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/GenerateSecretKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).GenerateSecretKey(ctx, req.(*GenerateSecretKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_Keys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Keys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/Keys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Keys(ctx, req.(*SecretKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_FetchNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).FetchNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/FetchNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).FetchNote(ctx, req.(*FetchNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_DecryptNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).DecryptNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/DecryptNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).DecryptNote(ctx, req.(*DecryptNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_OwnedNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OwnedNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).OwnedNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/OwnedNotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).OwnedNotes(ctx, req.(*OwnedNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_FullScanOwnedNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).FullScanOwnedNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/FullScanOwnedNotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).FullScanOwnedNotes(ctx, req.(*ViewKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_NewTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).NewTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/NewTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).NewTransaction(ctx, req.(*NewTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_VerifyTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).VerifyTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.Rusk/VerifyTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).VerifyTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rusk_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rusk.Rusk",
	HandlerType: (*RuskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Rusk_Echo_Handler,
		},
		{
			MethodName: "ValidateStateTransition",
			Handler:    _Rusk_ValidateStateTransition_Handler,
		},
		{
			MethodName: "GenerateSecretKey",
			Handler:    _Rusk_GenerateSecretKey_Handler,
		},
		{
			MethodName: "Keys",
			Handler:    _Rusk_Keys_Handler,
		},
		{
			MethodName: "FetchNote",
			Handler:    _Rusk_FetchNote_Handler,
		},
		{
			MethodName: "DecryptNote",
			Handler:    _Rusk_DecryptNote_Handler,
		},
		{
			MethodName: "OwnedNotes",
			Handler:    _Rusk_OwnedNotes_Handler,
		},
		{
			MethodName: "FullScanOwnedNotes",
			Handler:    _Rusk_FullScanOwnedNotes_Handler,
		},
		{
			MethodName: "NewTransaction",
			Handler:    _Rusk_NewTransaction_Handler,
		},
		{
			MethodName: "VerifyTransaction",
			Handler:    _Rusk_VerifyTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rusk.proto",
}
