// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consensus.proto

package rusk

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Call during block generation
type DistributeRequest struct {
	TotalReward           uint64       `protobuf:"fixed64,1,opt,name=total_reward,json=totalReward,proto3" json:"total_reward,omitempty"`
	ProvisionersAddresses []byte       `protobuf:"bytes,2,opt,name=provisioners_addresses,json=provisionersAddresses,proto3" json:"provisioners_addresses,omitempty"`
	BgPk                  *PublicKey   `protobuf:"bytes,3,opt,name=bg_pk,json=bgPk,proto3" json:"bg_pk,omitempty"`
	Tx                    *Transaction `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}     `json:"-"`
	XXX_unrecognized      []byte       `json:"-"`
	XXX_sizecache         int32        `json:"-"`
}

func (m *DistributeRequest) Reset()         { *m = DistributeRequest{} }
func (m *DistributeRequest) String() string { return proto.CompactTextString(m) }
func (*DistributeRequest) ProtoMessage()    {}
func (*DistributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f0f2c53b3de771, []int{0}
}

func (m *DistributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeRequest.Unmarshal(m, b)
}
func (m *DistributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeRequest.Marshal(b, m, deterministic)
}
func (m *DistributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeRequest.Merge(m, src)
}
func (m *DistributeRequest) XXX_Size() int {
	return xxx_messageInfo_DistributeRequest.Size(m)
}
func (m *DistributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeRequest proto.InternalMessageInfo

func (m *DistributeRequest) GetTotalReward() uint64 {
	if m != nil {
		return m.TotalReward
	}
	return 0
}

func (m *DistributeRequest) GetProvisionersAddresses() []byte {
	if m != nil {
		return m.ProvisionersAddresses
	}
	return nil
}

func (m *DistributeRequest) GetBgPk() *PublicKey {
	if m != nil {
		return m.BgPk
	}
	return nil
}

func (m *DistributeRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

// Call from consensus
type WithdrawRequest struct {
	BlsKey               []byte       `protobuf:"bytes,1,opt,name=bls_key,json=blsKey,proto3" json:"bls_key,omitempty"`
	Sig                  []byte       `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	Msg                  []byte       `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Tx                   *Transaction `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f0f2c53b3de771, []int{1}
}

func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(m, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetBlsKey() []byte {
	if m != nil {
		return m.BlsKey
	}
	return nil
}

func (m *WithdrawRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *WithdrawRequest) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *WithdrawRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

// Call from consensus
type StakeRequest struct {
	BlsKey               []byte       `protobuf:"bytes,1,opt,name=bls_key,json=blsKey,proto3" json:"bls_key,omitempty"`
	Value                uint64       `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	ExpirationHeight     uint64       `protobuf:"fixed64,3,opt,name=expiration_height,json=expirationHeight,proto3" json:"expiration_height,omitempty"`
	Tx                   *Transaction `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StakeRequest) Reset()         { *m = StakeRequest{} }
func (m *StakeRequest) String() string { return proto.CompactTextString(m) }
func (*StakeRequest) ProtoMessage()    {}
func (*StakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f0f2c53b3de771, []int{2}
}

func (m *StakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeRequest.Unmarshal(m, b)
}
func (m *StakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeRequest.Marshal(b, m, deterministic)
}
func (m *StakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeRequest.Merge(m, src)
}
func (m *StakeRequest) XXX_Size() int {
	return xxx_messageInfo_StakeRequest.Size(m)
}
func (m *StakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StakeRequest proto.InternalMessageInfo

func (m *StakeRequest) GetBlsKey() []byte {
	if m != nil {
		return m.BlsKey
	}
	return nil
}

func (m *StakeRequest) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *StakeRequest) GetExpirationHeight() uint64 {
	if m != nil {
		return m.ExpirationHeight
	}
	return 0
}

func (m *StakeRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

// Call from consensus
type WithdrawStakeRequest struct {
	BlsKey               []byte       `protobuf:"bytes,1,opt,name=bls_key,json=blsKey,proto3" json:"bls_key,omitempty"`
	Sig                  []byte       `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	Tx                   *Transaction `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WithdrawStakeRequest) Reset()         { *m = WithdrawStakeRequest{} }
func (m *WithdrawStakeRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawStakeRequest) ProtoMessage()    {}
func (*WithdrawStakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f0f2c53b3de771, []int{3}
}

func (m *WithdrawStakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawStakeRequest.Unmarshal(m, b)
}
func (m *WithdrawStakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawStakeRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawStakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawStakeRequest.Merge(m, src)
}
func (m *WithdrawStakeRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawStakeRequest.Size(m)
}
func (m *WithdrawStakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawStakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawStakeRequest proto.InternalMessageInfo

func (m *WithdrawStakeRequest) GetBlsKey() []byte {
	if m != nil {
		return m.BlsKey
	}
	return nil
}

func (m *WithdrawStakeRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *WithdrawStakeRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

// Call from consensus
type SlashRequest struct {
	BlsKey               []byte       `protobuf:"bytes,1,opt,name=bls_key,json=blsKey,proto3" json:"bls_key,omitempty"`
	Step                 uint32       `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Round                uint64       `protobuf:"fixed64,3,opt,name=round,proto3" json:"round,omitempty"`
	FirstMsg             []byte       `protobuf:"bytes,4,opt,name=first_msg,json=firstMsg,proto3" json:"first_msg,omitempty"`
	FirstSig             []byte       `protobuf:"bytes,5,opt,name=first_sig,json=firstSig,proto3" json:"first_sig,omitempty"`
	SecondMsg            []byte       `protobuf:"bytes,6,opt,name=second_msg,json=secondMsg,proto3" json:"second_msg,omitempty"`
	SecondSig            []byte       `protobuf:"bytes,7,opt,name=second_sig,json=secondSig,proto3" json:"second_sig,omitempty"`
	Tx                   *Transaction `protobuf:"bytes,8,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SlashRequest) Reset()         { *m = SlashRequest{} }
func (m *SlashRequest) String() string { return proto.CompactTextString(m) }
func (*SlashRequest) ProtoMessage()    {}
func (*SlashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f0f2c53b3de771, []int{4}
}

func (m *SlashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlashRequest.Unmarshal(m, b)
}
func (m *SlashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlashRequest.Marshal(b, m, deterministic)
}
func (m *SlashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlashRequest.Merge(m, src)
}
func (m *SlashRequest) XXX_Size() int {
	return xxx_messageInfo_SlashRequest.Size(m)
}
func (m *SlashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SlashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SlashRequest proto.InternalMessageInfo

func (m *SlashRequest) GetBlsKey() []byte {
	if m != nil {
		return m.BlsKey
	}
	return nil
}

func (m *SlashRequest) GetStep() uint32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *SlashRequest) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *SlashRequest) GetFirstMsg() []byte {
	if m != nil {
		return m.FirstMsg
	}
	return nil
}

func (m *SlashRequest) GetFirstSig() []byte {
	if m != nil {
		return m.FirstSig
	}
	return nil
}

func (m *SlashRequest) GetSecondMsg() []byte {
	if m != nil {
		return m.SecondMsg
	}
	return nil
}

func (m *SlashRequest) GetSecondSig() []byte {
	if m != nil {
		return m.SecondSig
	}
	return nil
}

func (m *SlashRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

// Call from block generator
type BidRequest struct {
	M                    []byte       `protobuf:"bytes,1,opt,name=m,proto3" json:"m,omitempty"`
	Commitment           []byte       `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	EncryptedValue       []byte       `protobuf:"bytes,3,opt,name=encrypted_value,json=encryptedValue,proto3" json:"encrypted_value,omitempty"`
	EncryptedBlinder     []byte       `protobuf:"bytes,4,opt,name=encrypted_blinder,json=encryptedBlinder,proto3" json:"encrypted_blinder,omitempty"`
	ExpirationHeight     uint64       `protobuf:"fixed64,5,opt,name=expiration_height,json=expirationHeight,proto3" json:"expiration_height,omitempty"`
	Pk                   []byte       `protobuf:"bytes,6,opt,name=pk,proto3" json:"pk,omitempty"`
	R                    []byte       `protobuf:"bytes,7,opt,name=r,proto3" json:"r,omitempty"`
	Z                    []byte       `protobuf:"bytes,8,opt,name=z,proto3" json:"z,omitempty"`
	Tx                   *Transaction `protobuf:"bytes,9,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BidRequest) Reset()         { *m = BidRequest{} }
func (m *BidRequest) String() string { return proto.CompactTextString(m) }
func (*BidRequest) ProtoMessage()    {}
func (*BidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f0f2c53b3de771, []int{5}
}

func (m *BidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidRequest.Unmarshal(m, b)
}
func (m *BidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidRequest.Marshal(b, m, deterministic)
}
func (m *BidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidRequest.Merge(m, src)
}
func (m *BidRequest) XXX_Size() int {
	return xxx_messageInfo_BidRequest.Size(m)
}
func (m *BidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BidRequest proto.InternalMessageInfo

func (m *BidRequest) GetM() []byte {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *BidRequest) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

func (m *BidRequest) GetEncryptedValue() []byte {
	if m != nil {
		return m.EncryptedValue
	}
	return nil
}

func (m *BidRequest) GetEncryptedBlinder() []byte {
	if m != nil {
		return m.EncryptedBlinder
	}
	return nil
}

func (m *BidRequest) GetExpirationHeight() uint64 {
	if m != nil {
		return m.ExpirationHeight
	}
	return 0
}

func (m *BidRequest) GetPk() []byte {
	if m != nil {
		return m.Pk
	}
	return nil
}

func (m *BidRequest) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *BidRequest) GetZ() []byte {
	if m != nil {
		return m.Z
	}
	return nil
}

func (m *BidRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

// Call from block generator
type WithdrawBidRequest struct {
	Commitment           []byte       `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	EncryptedValue       []byte       `protobuf:"bytes,2,opt,name=encrypted_value,json=encryptedValue,proto3" json:"encrypted_value,omitempty"`
	EncryptedBlinder     []byte       `protobuf:"bytes,3,opt,name=encrypted_blinder,json=encryptedBlinder,proto3" json:"encrypted_blinder,omitempty"`
	Bid                  []byte       `protobuf:"bytes,4,opt,name=bid,proto3" json:"bid,omitempty"`
	Sig                  []byte       `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	Tx                   *Transaction `protobuf:"bytes,6,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WithdrawBidRequest) Reset()         { *m = WithdrawBidRequest{} }
func (m *WithdrawBidRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawBidRequest) ProtoMessage()    {}
func (*WithdrawBidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f0f2c53b3de771, []int{6}
}

func (m *WithdrawBidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawBidRequest.Unmarshal(m, b)
}
func (m *WithdrawBidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawBidRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawBidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawBidRequest.Merge(m, src)
}
func (m *WithdrawBidRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawBidRequest.Size(m)
}
func (m *WithdrawBidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawBidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawBidRequest proto.InternalMessageInfo

func (m *WithdrawBidRequest) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

func (m *WithdrawBidRequest) GetEncryptedValue() []byte {
	if m != nil {
		return m.EncryptedValue
	}
	return nil
}

func (m *WithdrawBidRequest) GetEncryptedBlinder() []byte {
	if m != nil {
		return m.EncryptedBlinder
	}
	return nil
}

func (m *WithdrawBidRequest) GetBid() []byte {
	if m != nil {
		return m.Bid
	}
	return nil
}

func (m *WithdrawBidRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *WithdrawBidRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func init() {
	proto.RegisterType((*DistributeRequest)(nil), "rusk.DistributeRequest")
	proto.RegisterType((*WithdrawRequest)(nil), "rusk.WithdrawRequest")
	proto.RegisterType((*StakeRequest)(nil), "rusk.StakeRequest")
	proto.RegisterType((*WithdrawStakeRequest)(nil), "rusk.WithdrawStakeRequest")
	proto.RegisterType((*SlashRequest)(nil), "rusk.SlashRequest")
	proto.RegisterType((*BidRequest)(nil), "rusk.BidRequest")
	proto.RegisterType((*WithdrawBidRequest)(nil), "rusk.WithdrawBidRequest")
}

func init() {
	proto.RegisterFile("consensus.proto", fileDescriptor_56f0f2c53b3de771)
}

var fileDescriptor_56f0f2c53b3de771 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdf, 0x6e, 0xd3, 0x3e,
	0x18, 0x95, 0xd3, 0x36, 0x5b, 0xbf, 0xe5, 0xb7, 0xb6, 0xd6, 0x7e, 0x50, 0x0d, 0x81, 0xba, 0x09,
	0x89, 0x4a, 0x48, 0xbd, 0x00, 0xf1, 0x00, 0x4c, 0x5c, 0x20, 0x4d, 0x48, 0x93, 0x8b, 0xe0, 0x32,
	0x4a, 0xe2, 0x8f, 0xd4, 0xca, 0xdf, 0xd9, 0xce, 0xd6, 0xee, 0x19, 0xe0, 0x75, 0x78, 0x0f, 0xde,
	0x83, 0x87, 0x40, 0x76, 0x92, 0xb6, 0xfc, 0x59, 0xd7, 0x3b, 0xfb, 0x1c, 0xdb, 0xdf, 0x39, 0x27,
	0x47, 0x81, 0x41, 0x54, 0xe4, 0x0a, 0x73, 0x55, 0xa9, 0x59, 0x29, 0x0b, 0x5d, 0xd0, 0xae, 0xac,
	0x54, 0x72, 0x3a, 0xd2, 0x32, 0xc8, 0x55, 0x10, 0x69, 0x51, 0xe4, 0x35, 0x71, 0x0a, 0x09, 0xae,
	0x9a, 0x43, 0xe7, 0xdf, 0x09, 0x8c, 0xde, 0x09, 0xa5, 0xa5, 0x08, 0x2b, 0x8d, 0x0c, 0xaf, 0x2b,
	0x54, 0x9a, 0x9e, 0x81, 0xa7, 0x0b, 0x1d, 0xa4, 0xbe, 0xc4, 0xdb, 0x40, 0xf2, 0x31, 0x99, 0x90,
	0xa9, 0xcb, 0x8e, 0x2c, 0xc6, 0x2c, 0x44, 0xdf, 0xc0, 0xa3, 0x52, 0x16, 0x37, 0x42, 0x89, 0x22,
	0x47, 0xa9, 0xfc, 0x80, 0x73, 0x89, 0x4a, 0xa1, 0x1a, 0x3b, 0x13, 0x32, 0xf5, 0xd8, 0xff, 0xdb,
	0xec, 0xdb, 0x96, 0xa4, 0xcf, 0xa1, 0x17, 0xc6, 0x7e, 0x99, 0x8c, 0x3b, 0x13, 0x32, 0x3d, 0x7a,
	0x35, 0x98, 0x19, 0x91, 0xb3, 0xab, 0x2a, 0x4c, 0x45, 0x74, 0x89, 0x2b, 0xd6, 0x0d, 0xe3, 0xab,
	0x84, 0x9e, 0x81, 0xa3, 0x97, 0xe3, 0xae, 0x3d, 0x32, 0xaa, 0x8f, 0x7c, 0xdc, 0xd8, 0x60, 0x8e,
	0x5e, 0x9e, 0x5f, 0xc3, 0xe0, 0xb3, 0xd0, 0x0b, 0x2e, 0x83, 0xdb, 0x56, 0xf5, 0x63, 0x38, 0x08,
	0x53, 0xe5, 0x27, 0xb8, 0xb2, 0x82, 0x3d, 0xe6, 0x86, 0xa9, 0xba, 0xc4, 0x15, 0x1d, 0x42, 0x47,
	0x89, 0xb8, 0x11, 0x66, 0x96, 0x06, 0xc9, 0x54, 0x6c, 0x45, 0x78, 0xcc, 0x2c, 0xf7, 0x19, 0xf9,
	0x8d, 0x80, 0x37, 0xd7, 0x41, 0x82, 0x0f, 0x0e, 0x3c, 0x81, 0xde, 0x4d, 0x90, 0x56, 0x68, 0x47,
	0xba, 0xac, 0xde, 0xd0, 0x97, 0x30, 0xc2, 0x65, 0x29, 0x64, 0x60, 0x5e, 0xf4, 0x17, 0x28, 0xe2,
	0x85, 0xb6, 0x12, 0x5c, 0x36, 0xdc, 0x10, 0xef, 0x2d, 0xbe, 0x8f, 0x1e, 0x0e, 0x27, 0x6d, 0x04,
	0xfb, 0xc9, 0xfa, 0x3b, 0x87, 0x7a, 0x4a, 0x67, 0xd7, 0x94, 0x9f, 0xc6, 0x75, 0x1a, 0xa8, 0xc5,
	0x83, 0xcf, 0x53, 0xe8, 0x2a, 0x8d, 0xa5, 0x7d, 0xff, 0x3f, 0x66, 0xd7, 0x26, 0x09, 0x59, 0x54,
	0x39, 0x6f, 0x7c, 0xd6, 0x1b, 0xfa, 0x04, 0xfa, 0x5f, 0x84, 0x54, 0xda, 0x37, 0x1f, 0xa1, 0x6b,
	0x1f, 0x39, 0xb4, 0xc0, 0x07, 0x15, 0x6f, 0x48, 0xa3, 0xb5, 0xb7, 0x45, 0xce, 0x45, 0x4c, 0x9f,
	0x02, 0x28, 0x8c, 0x8a, 0x9c, 0xdb, 0xab, 0xae, 0x65, 0xfb, 0x35, 0x62, 0xee, 0x6e, 0x68, 0x73,
	0xf9, 0x60, 0x9b, 0x9e, 0xaf, 0xed, 0x1e, 0xee, 0xb2, 0xfb, 0xd5, 0x01, 0xb8, 0x10, 0xbc, 0x35,
	0xeb, 0x01, 0xc9, 0x1a, 0x9b, 0x24, 0xa3, 0xcf, 0x00, 0xa2, 0x22, 0xcb, 0x84, 0xce, 0x30, 0xd7,
	0x4d, 0x8e, 0x5b, 0x08, 0x7d, 0x01, 0x03, 0xcc, 0x23, 0xb9, 0x2a, 0x35, 0x72, 0xbf, 0x6e, 0x40,
	0x5d, 0xb1, 0xe3, 0x35, 0xfc, 0x69, 0x5d, 0x85, 0xf5, 0xc1, 0x30, 0x15, 0x39, 0x47, 0xd9, 0x04,
	0x31, 0x5c, 0x13, 0x17, 0x35, 0xfe, 0xef, 0xde, 0xf4, 0xee, 0xe9, 0xcd, 0x31, 0x38, 0x65, 0xd2,
	0x04, 0xe3, 0x94, 0x89, 0x31, 0x20, 0x9b, 0x20, 0x88, 0x34, 0xbb, 0x3b, 0xeb, 0xdf, 0x63, 0xe4,
	0xae, 0x89, 0xa3, 0xbf, 0x2b, 0x8e, 0x1f, 0x04, 0x68, 0x5b, 0xb2, 0xad, 0x58, 0x7e, 0x0f, 0x82,
	0xec, 0x13, 0x84, 0xb3, 0x7f, 0x10, 0x9d, 0x7b, 0x82, 0x18, 0x42, 0x27, 0x14, 0xbc, 0xc9, 0xc9,
	0x2c, 0xdb, 0x46, 0xf7, 0xfe, 0x6c, 0xb4, 0xbb, 0xc3, 0x53, 0xe8, 0xda, 0x5f, 0xdf, 0xeb, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x1b, 0xb9, 0xa1, 0x32, 0x05, 0x00, 0x00,
}
