// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mempool.proto

package node

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TxType int32

const (
	// CoinbaseType is the identifier for a block coinbase
	TxType_COINBASE TxType = 0
	// BidType is the identifier for a blind bid
	TxType_BID TxType = 1
	// StakeType is the identifier for a stake
	TxType_STAKE TxType = 2
	// StandardType is the identifier for a standard transaction
	TxType_STANDARD TxType = 3
	// TimelockType is the identifier for a standard time-locked transaction
	TxType_TIMELOCK TxType = 4
	// ContractType is the identifier for a smart contract transaction
	TxType_CONTRACT TxType = 5
)

var TxType_name = map[int32]string{
	0: "COINBASE",
	1: "BID",
	2: "STAKE",
	3: "STANDARD",
	4: "TIMELOCK",
	5: "CONTRACT",
}

var TxType_value = map[string]int32{
	"COINBASE": 0,
	"BID":      1,
	"STAKE":    2,
	"STANDARD": 3,
	"TIMELOCK": 4,
	"CONTRACT": 5,
}

func (x TxType) String() string {
	return proto.EnumName(TxType_name, int32(x))
}

func (TxType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{0}
}

type Tx struct {
	Type                 TxType   `protobuf:"varint,1,opt,name=type,proto3,enum=node.TxType" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	LockTime             uint64   `protobuf:"fixed64,3,opt,name=lock_time,json=lockTime,proto3" json:"lock_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{0}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetType() TxType {
	if m != nil {
		return m.Type
	}
	return TxType_COINBASE
}

func (m *Tx) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tx) GetLockTime() uint64 {
	if m != nil {
		return m.LockTime
	}
	return 0
}

// SelectRequest can specify an ID or a transaction type or none
type SelectRequest struct {
	Types                []TxType `protobuf:"varint,1,rep,packed,name=types,proto3,enum=node.TxType" json:"types,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectRequest) Reset()         { *m = SelectRequest{} }
func (m *SelectRequest) String() string { return proto.CompactTextString(m) }
func (*SelectRequest) ProtoMessage()    {}
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{1}
}
func (m *SelectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectRequest.Unmarshal(m, b)
}
func (m *SelectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectRequest.Marshal(b, m, deterministic)
}
func (m *SelectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectRequest.Merge(m, src)
}
func (m *SelectRequest) XXX_Size() int {
	return xxx_messageInfo_SelectRequest.Size(m)
}
func (m *SelectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectRequest proto.InternalMessageInfo

func (m *SelectRequest) GetTypes() []TxType {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *SelectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SelectResponse struct {
	//Note: the response was a single string describing the transactions.
	//It should actually be responsibility of the caller to format the data or handle it otherwise
	//string msg = 1;
	Result               []*Tx    `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectResponse) Reset()         { *m = SelectResponse{} }
func (m *SelectResponse) String() string { return proto.CompactTextString(m) }
func (*SelectResponse) ProtoMessage()    {}
func (*SelectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{2}
}
func (m *SelectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectResponse.Unmarshal(m, b)
}
func (m *SelectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectResponse.Marshal(b, m, deterministic)
}
func (m *SelectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectResponse.Merge(m, src)
}
func (m *SelectResponse) XXX_Size() int {
	return xxx_messageInfo_SelectResponse.Size(m)
}
func (m *SelectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SelectResponse proto.InternalMessageInfo

func (m *SelectResponse) GetResult() []*Tx {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterEnum("node.TxType", TxType_name, TxType_value)
	proto.RegisterType((*Tx)(nil), "node.Tx")
	proto.RegisterType((*SelectRequest)(nil), "node.SelectRequest")
	proto.RegisterType((*SelectResponse)(nil), "node.SelectResponse")
}

func init() { proto.RegisterFile("mempool.proto", fileDescriptor_a84c3667d8c2093a) }

var fileDescriptor_a84c3667d8c2093a = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x6f, 0x82, 0x30,
	0x14, 0xc7, 0x07, 0x28, 0xd3, 0x37, 0x35, 0x4d, 0x4f, 0x24, 0xbb, 0x34, 0x9c, 0x88, 0xc9, 0x20,
	0x71, 0x9f, 0x00, 0xd1, 0x83, 0x71, 0xd3, 0xa4, 0xf4, 0xb4, 0xcb, 0x32, 0xe5, 0xcd, 0x11, 0xc1,
	0x32, 0xdb, 0x26, 0xfa, 0xed, 0x97, 0xc2, 0xbc, 0x6c, 0xc7, 0xfe, 0x7f, 0x7d, 0xbf, 0xff, 0xcb,
	0x83, 0x71, 0x8d, 0x75, 0x23, 0x65, 0x15, 0x37, 0x67, 0xa9, 0x25, 0xed, 0x9d, 0x64, 0x81, 0x61,
	0x0e, 0xae, 0xb8, 0x50, 0x06, 0x3d, 0x7d, 0x6d, 0x30, 0x70, 0x98, 0x13, 0x4d, 0x66, 0xa3, 0xd8,
	0xa2, 0x58, 0x5c, 0xc4, 0xb5, 0x41, 0xde, 0x12, 0x3a, 0x01, 0xb7, 0x2c, 0x02, 0x97, 0x39, 0xd1,
	0x90, 0xbb, 0x65, 0x41, 0x1f, 0x61, 0x58, 0xc9, 0xfd, 0xf1, 0x5d, 0x97, 0x35, 0x06, 0x1e, 0x73,
	0x22, 0x9f, 0x0f, 0x6c, 0x20, 0xca, 0x1a, 0xc3, 0x0c, 0xc6, 0x39, 0x56, 0xb8, 0xd7, 0x1c, 0xbf,
	0x0d, 0x2a, 0x4d, 0x43, 0xe8, 0x5b, 0x8b, 0x0a, 0x1c, 0xe6, 0xfd, 0x2b, 0xe8, 0xd0, 0xdf, 0x86,
	0x70, 0x06, 0x93, 0x9b, 0x44, 0x35, 0xf2, 0xa4, 0x90, 0x32, 0xf0, 0xcf, 0xa8, 0x4c, 0xa5, 0x5b,
	0xcd, 0xc3, 0x6c, 0x70, 0xd3, 0xf0, 0xdf, 0x7c, 0x2a, 0xc0, 0xef, 0xa4, 0x74, 0x04, 0x83, 0x6c,
	0xbb, 0xda, 0xcc, 0xd3, 0x7c, 0x49, 0xee, 0xe8, 0x3d, 0x78, 0xf3, 0xd5, 0x82, 0x38, 0x74, 0x08,
	0xfd, 0x5c, 0xa4, 0xeb, 0x25, 0x71, 0xed, 0x8f, 0x5c, 0xa4, 0x9b, 0x45, 0xca, 0x17, 0xc4, 0xb3,
	0x2f, 0xb1, 0x7a, 0x5d, 0xbe, 0x6c, 0xb3, 0x35, 0xe9, 0x75, 0xd3, 0x1b, 0xc1, 0xd3, 0x4c, 0x90,
	0xfe, 0x7c, 0xfa, 0x16, 0x1d, 0x4a, 0xfd, 0x65, 0x76, 0xf1, 0x5e, 0xd6, 0x49, 0x61, 0xd4, 0xf1,
	0xa9, 0x3d, 0xe1, 0xce, 0x7c, 0x26, 0x1f, 0x46, 0xcb, 0x03, 0x9e, 0x92, 0x83, 0x4c, 0xec, 0x32,
	0x3b, 0xbf, 0x25, 0xcf, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xac, 0x76, 0x4f, 0x6d, 0x01,
	0x00, 0x00,
}
